version: "3.9"

services:
  node: 
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      - node_postgres_network
    ports: 
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  
  postgres: 
    build:
      dockerfile: Dockerfile
      context: ./db/
    # command: -p ${POSTGRES_PORT}
    restart: always
    networks:
      - node_postgres_network
    ports: 
      # - ${POSTGRES_PORT}:${POSTGRES_PORT}
      - "5001:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d

networks:
  node_postgres_network:

  # host:"postgres"